package com.bank.bian.enterpriseplanning;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Enterprise Planning
 *
 * Business Area:      Business Support
 * Business Domain:    Business Command and Control
 * Functional Pattern: Plan
 * Asset Type:         Enterprise Plan
 * Control Record:     Enterprise Plan Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Enterprise Planning — BIAN Semantic API")
                .description("Service Domain 'Enterprise Planning' (Plan pattern) "
                        + "operating on the 'Enterprise Plan Plan' control record.")
                .version("0.1.0"));
    }
}
